name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: 'experimental-features = nix-command flakes'
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Run tests
        run: nix develop -c cargo test --locked --all-features

  static-check-windows:
    strategy:
      matrix:
        os:
          - windows-latest
          - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --locked --all-features
