name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - windows-2019
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute by OpenSSL (macOS, Ubuntu)
        if: ${{ ! startsWith(matrix.os, 'windows') }}
        run: |
          find ./tests/fixtures/ -type f \
            | xargs -I {} openssl dgst -sha256 {} \
            | sort
      - name: Compute by Get-FileHash (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          powershell.exe -Command "Get-ChildItem -Recurse -File .\tests\fixtures\ | Get-FileHash -Algorithm SHA256 | Sort-Object Path | Select-Object Hash,Path"

      - uses: MinoruSekine/setup-scoop@v3
        if: ${{ startsWith(matrix.os, 'windows') }}
      - name: Compute by OpenSSL (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          scoop install openssl
          Get-ChildItem -Recurse -File .\tests\fixtures\ | % { openssl dgst -sha256 $_.FullName }

      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --locked --all-features
